####  application-dev.yml
server:
  port: 8002

logging:
  pattern:
    console: "%clr(%5p) %clr(-){faint} %clr(%-80.80logger{79}){cyan} %clr(:) %m%n"

spring:
  application:
    name: service-video
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

#定义oss相关属性
oss:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:
  cosRegion:

#定义minio相关属性
minio:
  endPoint:
  secretId:
  secretKey:
  bucketName:
  cosRegion:
  port: